In [1]:
import numpy as np

# Mathmatical and Statistical in NumPy

In [17]:
np.set_printoptions(precision=4)
array = np.random.randn(4,5)
array

array([[-2.0647,  0.1176,  0.7351, -0.48  ,  0.35  ],
       [-1.5535, -1.8657, -0.7927,  0.4818, -0.4849],
       [-0.8588, -0.1103, -1.3804,  0.7142, -0.7979],
       [-0.1266,  0.5387, -1.134 ,  0.2811, -0.3727]])

## Mean

In [19]:
array.mean()

-0.44018468864191507

In [20]:
np.mean(array)

-0.44018468864191507

# Meadian

In [21]:
np.median(array)

-0.4263587966617228

# Min

In [22]:
array.min()

-2.064696608560577

# Max


In [23]:
array.max()

0.735102668899207

# Standard Deviation

In [24]:
array.std()

0.8335622352202574

# Index of minimum and maximum value

In [13]:
array1 = np.random.randint(50,size=(10))
array1

array([19, 49, 38,  1, 21, 49, 11, 38, 43,  9])

In [14]:
array1.min()

1

In [15]:
array1.argmin()

3

In [16]:
array1.argmax()

1

# Sum of rows

In [18]:
array.sum(axis = 0)

array([-4.6036, -1.3198, -2.5719,  0.9971, -1.3056])

# Sum of columns

In [25]:
array.sum(axis = 1)

array([-1.342 , -4.2149, -2.4332, -0.8135])

## If we have array of boolean sum() will return the count of True

In [28]:
array2 = np.array([True,False,True])
array2

array([ True, False,  True])

In [29]:
array2.sum()

2

# Any () <br>
It will return true if any value is true

In [30]:
array2.any()

True

# All () <br>
It will return true if all values is true

In [31]:
array2.all()

False