In [1]:
import numpy as np

# Sorting NumPy Arrays

In [2]:
array = np.random.randn(5)
array

array([-0.05156031,  0.24018572, -0.72939004, -0.26642958,  0.71732645])

In [4]:
array.sort() #this method manipulates the original array
array

array([-0.72939004, -0.26642958, -0.05156031,  0.24018572,  0.71732645])

# Ascending order

In [7]:
np.sort(array) #this method do not manipulates the original array

array([-0.72939004, -0.26642958, -0.05156031,  0.24018572,  0.71732645])

# Descending order

In [8]:
np.sort(array)[::-1]

array([ 0.71732645,  0.24018572, -0.05156031, -0.26642958, -0.72939004])

In [13]:
array2 = np.random.randint(20,size= (3,3))
array2

array([[15,  0, 13],
       [ 4,  8,  9],
       [ 4, 11,  5]])

# Sorting along with columns and rows

In [14]:
array2.sort(1)
array2

array([[ 0, 13, 15],
       [ 4,  8,  9],
       [ 4,  5, 11]])

In [15]:
array2.sort(0)
array2

array([[ 0,  5,  9],
       [ 4,  8, 11],
       [ 4, 13, 15]])

# Unique

In [16]:
np.unique(array2)

array([ 0,  4,  5,  8,  9, 11, 13, 15])