In [1]:
import numpy as np

# Arithmetic Operation in NumPy

In [5]:
list1 = [[1,2,3],[4,5,6]]
array = np.array(list1)
array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array.ndim

2

## Multiplication

In [6]:
array * array

array([[ 1,  4,  9],
       [16, 25, 36]])

## Substraction

In [7]:
array - array

array([[0, 0, 0],
       [0, 0, 0]])

## Addition

In [11]:
array + array

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Division

In [13]:
array / array

array([[1., 1., 1.],
       [1., 1., 1.]])

# Broadcasting

In [12]:
array + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
array - 1

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
array / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [15]:
array * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [16]:
array ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [17]:
array > 3

array([[False, False, False],
       [ True,  True,  True]])