In [1]:
import numpy as np

# Indexing

In [7]:
array = np.arange(2,20,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
array[4]

10

# Slicing

In [10]:
array[4:8]

array([10, 12, 14, 16])

In [14]:
array[:4]

array([2, 4, 6, 8])

In [13]:
array[4:]

array([10, 12, 14, 16, 18])

In [15]:
array[:]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

## A slice is a mirror not a copy.
<br>Lets See

In [19]:
slice1 = array[2:6]
slice1

array([ 6,  8, 10, 12])

In [21]:
slice1[0] = 99
slice1

array([99,  8, 10, 12])

In [22]:
array

array([ 2,  4, 99,  8, 10, 12, 14, 16, 18])

## If you do not want to reflect changes in orignal array
<br>Lets See

In [23]:
slice2 = array[2:6].copy()

In [24]:
slice2

array([99,  8, 10, 12])

<br><br>

# 2-D Array Indexing and Slicing

In [26]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
array2[2,1]

8

## Slicing all rows and columns

In [27]:
array2[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Slicing first 2 rows and all columns

In [29]:
array2[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

## Slicing all rows and all columns except 1 column

In [31]:
array2[:,1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

## Slicing all rows and 2nd column

In [35]:
array2[:,1:2]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

## Slicing elements (5,6,8,9)

In [36]:
array2[1:3,1:]

array([[5, 6],
       [8, 9]])