In [1]:
import numpy as np

# Boolean Indexing in NumPy 
<br> Boolean indexing always makes a new copy of data

In [2]:
array1 = np.array(['a','b','c','a','d','b','a'])
array1

array(['a', 'b', 'c', 'a', 'd', 'b', 'a'], dtype='<U1')

In [7]:
array2 = np.array([22,45,22,61,19,23,31])
array2

array([22, 45, 22, 61, 19, 23, 31])

Note: Length of array must be same.(as here is 7 in both arrays.) 

In [8]:
array1 == 'a'

array([ True, False, False,  True, False, False,  True])

In [9]:
array2[array1 == 'a']

array([22, 61, 31])

In [12]:
# for 2-D arrays no. of rows are equal to the length of array
array3 = np.random.randn(7,2) 
array3

array([[-0.20742435, -0.4113353 ],
       [ 0.48939344, -1.94445137],
       [ 0.41962012, -0.34043125],
       [-1.26532532, -1.28851556],
       [ 0.17598314,  0.26238749],
       [ 0.2508142 , -0.09968164],
       [ 0.69985206, -1.03283076]])

In [13]:
array3[array1 == 'a']

array([[-0.20742435, -0.4113353 ],
       [-1.26532532, -1.28851556],
       [ 0.69985206, -1.03283076]])

In [20]:
array4 = np.array([[1,23],[4,43],[1,17],[3,53],[5,23],[1,42],[3,35],[1,34],[4,41],[2,23]])
array4

array([[ 1, 23],
       [ 4, 43],
       [ 1, 17],
       [ 3, 53],
       [ 5, 23],
       [ 1, 42],
       [ 3, 35],
       [ 1, 34],
       [ 4, 41],
       [ 2, 23]])

In [21]:
array4.shape

(10, 2)

In [22]:
array4[:,0] == 1

array([ True, False,  True, False, False,  True, False,  True, False,
       False])

In [23]:
array4[array4[:,0] == 1]

array([[ 1, 23],
       [ 1, 17],
       [ 1, 42],
       [ 1, 34]])