In [1]:
import numpy as np

# Fancy Indexing

In [2]:
array = np.random.randint(50, size = (10))
array

array([ 3,  3, 12, 17,  1, 37, 11, 12, 32, 42])

In [4]:
index = [1,3,5,7]
array[index]

array([ 3, 17, 37, 12])

Note: Returned array always be the same shape of passed indexes

In [6]:
index2 = np.array([[1,3],[5,7]])
array[index2]

array([[ 3, 17],
       [37, 12]])

In [9]:
array2 = np.random.randint(100,size = (3,4))
array2

array([[70, 64,  3, 85],
       [80, 72, 77,  3],
       [27, 50, 55, 78]])

## Lets suppose we want multiple elements from this array <br>
i.e. 85, 77, 78

In [11]:
index3 = ((0,1,2),(3,2,3))
array2[index3]

array([85, 77, 78])

In [12]:
row = [0,1,2]
column = [3,2,3]
array2[row,column]

array([85, 77, 78])