In [4]:
import numpy as np

# Transposing Arrays

In [5]:
array = np.random.randint(20, size = (3,4))
array

array([[16,  4, 11, 19],
       [ 9, 11, 17, 18],
       [16, 16,  6,  6]])

In [7]:
array.transpose()

array([[16,  9, 16],
       [ 4, 11, 16],
       [11, 17,  6],
       [19, 18,  6]])

In [8]:
array.T

array([[16,  9, 16],
       [ 4, 11, 16],
       [11, 17,  6],
       [19, 18,  6]])

Note: 1-D array have no effect of using transpose